# Site settings
title: duncbell.com
email: duncan@duncbell.com
description: ""
baseurl: "" # the subpath of your site (e.g. /blog or /site)
url: "http://www.duncbell.com" # the base hostname & protocol for your site
twitter_username: duncbell
github_username:  dunc-bell

# Theme settings
theme: minima

#Code to get goodreads to work
kramdown:
  parse_block_html: true
  hard_wrap: false
  input: GFM
